### ISSUE TITLE
Custom Footer

### ISSUE THREAD

**Issue by NikKovIos** [airymiao/AiryRefreshControl#1]
Thank you for your work. What about setting custom footer refresh view?

**Comment by airymiao** [comment]
Thanks for your suggestion.I think that footer refresh view is just used to give a hint to user,and an activity indicator view is enough,so I don't create a custom footer refresh view.

**Comment by NikKovIos** [comment]
I think it's a good thing to have such a functional. Will you do it soon, or i should do it myself or  by another library?

**Comment by airymiao** [comment]
I will add this feature later.Maybe you can try [MJRefresh](https://github.com/CoderMJLee/MJRefresh) if you need.
